"""empty message

Revision ID: ff5efab8b8ff
Revises: cad35d2cb7e1
Create Date: 2020-10-19 07:38:37.768304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5efab8b8ff'
down_revision = 'cad35d2cb7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'link')
    # ### end Alembic commands ###
